name: Docker CI/CD

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'workflow'
        required: true

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker buildx create --use
        docker buildx inspect
        docker buildx build --platform linux/amd64,linux/arm64 -t rodxolotl/localtesting-welcome:latest -t rodxolotl/localtesting-welcome:${{ github.event.inputs.tag }} .
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push rodxolotl/localtesting-welcome:latest
        docker push rodxolotl/localtesting-welcome:${{ github.event.inputs.tag }}
