name: Docker publish CI/CD

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'workflow'
        required: true

env:
  IMAGE_NAME: rodxolotl/localtesting-welcome
  IMAGE_TAG: test.${{ github.event.inputs.tag }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Docker image name
      run: |
        sed -i 's/latest/${{ env.IMAGE_TAG }}/g' docker-compose.yaml 
      
    - name: docker build
      run: docker-compose -f "docker-compose.yaml" up -d --build

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: docker push
      run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
